# TeleAgent Review Sink —— 安装脚本（PowerShell）
#
# 做四件事：
#   1. 把 review-sink.js / watchdog.js 复制到安装目录
#   2. 写入 internal-debug.yaml（重定向审查接口到本机 sink）
#   3. 在启动文件夹放一个 VBS（开机自启 sink + 看门狗，隐藏窗口）
#   4. 立即拉起 sink + 看门狗
#
# 用法：以普通用户运行 install.cmd，或 PowerShell 里 .\install.ps1
#
# 卸载：uninstall.cmd（还原 internal-debug.yaml、删自启项、停服务）

[CmdletBinding()]
param(
	[int]$Port = 9923,
	[string]$InstallDir = ""
)

$ErrorActionPreference = "Stop"
$ErrorView = "NormalView"

# ---- 路径 -----------------------------------------------------------------

$TeleAgentDir = Join-Path $env:USERPROFILE ".local\share\TeleAgent"
$DebugFile = Join-Path $TeleAgentDir "internal-debug.yaml"

if ([string]::IsNullOrWhiteSpace($InstallDir)) {
	$InstallDir = Join-Path $env:USERPROFILE "teleagent-review-sink"
}
$StartupDir = [Environment]::GetFolderPath("Startup")
$VbsPath = Join-Path $StartupDir "teleagent-sink.vbs"

if (-not (Test-Path $TeleAgentDir)) {
	Write-Host "未找到 TeleAgent 数据目录：$TeleAgentDir" -ForegroundColor Red
	Write-Host "请先安装并运行一次 TeleAgent，再执行本安装。" -ForegroundColor Red
	exit 1
}

# TeleAgent 自带的 node 运行时（没有就用系统 node / 安装目录里的）
$TaNode = Join-Path $TeleAgentDir "runtimes\node\node.exe"
if (Test-Path $TaNode) {
	$NodeExe = $TaNode
} elseif ($PSVersionTable.PSEdition -eq "Core" -and $null -ne (Get-Command node -ErrorAction SilentlyContinue)) {
	$NodeExe = (Get-Command node).Source
} else {
	$NodeExe = "node"
}
Write-Host "Node 运行时：$NodeExe"

# ---- 1. 复制脚本 ----------------------------------------------------------

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item "$PSScriptRoot\review-sink.js" $InstallDir -Force
Copy-Item "$PSScriptRoot\watchdog.js" $InstallDir -Force

# 端口写进配置文件，脚本和 VBS 都读它
$Config = @{ port = $Port; upstreamHost = "agent.teleai.com.cn"; blockPaths = @("/security/") }
$Config | ConvertTo-Json | Set-Content (Join-Path $InstallDir "sink-config.json") -Encoding UTF8

# ---- 2. 写入 internal-debug.yaml ------------------------------------------

# 备份已有文件（不覆盖别人的备份）
if (Test-Path $DebugFile) {
	$Bak = "$DebugFile.bak"
	$i = 1
	while (Test-Path $Bak) { $Bak = "$DebugFile.bak$i"; $i++ }
	Copy-Item $DebugFile $Bak -Force
	Write-Host "已备份原配置到 $Bak" -ForegroundColor Yellow
}

$Base = "http://127.0.0.1:$Port"
@"
# TeleAgent 内部调试覆盖（设备级）—— teleagent-review-sink 生成
# 作用：把安全审查接口的基地址改到本地 sink，阻止本机数据外发。
# llmBaseUrl -> NewApi baseURL：内核的审查接口和对话都走它（对话被 sink 透传到真实网关）
# apiBaseUrl -> SuperAgentAPI baseURL：App 侧的审查 / 搜索走它
# 删除本文件即可恢复默认行为。
apiBaseUrl: $Base
llmBaseUrl: $Base/superCowork/sapi
"@ | Set-Content $DebugFile -Encoding UTF8
Write-Host "已写入 $DebugFile" -ForegroundColor Green

# ---- 3. 开机自启 VBS ------------------------------------------------------

$sinkQuoted = '"' + (Join-Path $InstallDir 'review-sink.js') + '"'
$wdQuoted = '"' + (Join-Path $InstallDir 'watchdog.js') + '"'
$nodeQuoted = '"' + $NodeExe + '"'
$vbs = @"
' teleagent-review-sink autostart + watchdog (hidden window)
' generated by install.ps1
Dim sh
Set sh = CreateObject("WScript.Shell")
sh.Run $nodeQuoted & " " & $sinkQuoted & " " & $Port, 0, False
sh.Run $nodeQuoted & " " & $wdQuoted, 0, False
"@
$vbs | Set-Content $VbsPath -Encoding Default
Write-Host "已写入自启项 $VbsPath" -ForegroundColor Green

# ---- 4. 立即拉起（用 WMI 脱离当前会话，避免被父进程连坐结束）----------------

function Start-Detached($Exe, $ArgList) {
	# WMI Create 的第一个参数必须是完整命令行，第二个是工作目录
	# WMI 启动的进程脱离当前会话，不会被父进程连坐结束
	# ShowWindow=0：强制隐藏，绝不弹控制台窗口
	$cmdLine = '"' + $Exe + '" ' + $ArgList
	$startup = ([wmiclass]"Win32_ProcessStartup").CreateInstance()
	$startup.ShowWindow = 0
	$r = ([wmiclass]"Win32_Process").Create($cmdLine, $InstallDir, $startup)
	if ($r.ReturnValue -ne 0) {
		Write-Host "WMI 启动失败($($r.ReturnValue))，改用 Start-Process" -ForegroundColor Yellow
		Start-Process -FilePath $Exe -ArgumentList $ArgList -WindowStyle Hidden
	} else {
		Write-Host "已启动进程 PID=$($r.ProcessId)（隐藏窗口）" -ForegroundColor Gray
	}
}
Start-Detached $NodeExe "$sinkQuoted $Port"
Start-Detached $NodeExe "$wdQuoted"

Start-Sleep -Seconds 2

# ---- 5. 状态检查 ----------------------------------------------------------

$up = Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue
if ($up.TcpTestSucceeded) {
	Write-Host ""
	Write-Host "安装完成，sink 已在 127.0.0.1:$Port 监听" -ForegroundColor Green
} else {
	Write-Host ""
	Write-Host "sink 似乎还没起来，请检查日志：$(Join-Path $InstallDir 'sink.log')" -ForegroundColor Red
}

Write-Host ""
Write-Host "重要：请重启一次 TeleAgent（托盘右键退出后重新打开），让新的接口地址生效。" -ForegroundColor Cyan
Write-Host "之后任何工具调用都不会再外发审查数据；重启机器后 sink 会自动随登录启动。" -ForegroundColor Cyan
Write-Host ""
Write-Host "审计日志：$(Join-Path $InstallDir 'sink.log')（BLOCK = 已拦截，PASS = 放行给真实网关）" -ForegroundColor Gray
